class StringConstant {
  static const welcome = "Welcome";
  static const back = 'Back!';
  static const font = 'montserrat';
  static const usernamelhint = "Username or Email";
  static const passhint = 'Password';
  static const forgetpass = 'Forget Password?';
  static const login = '  Login';
  static const continuewith = "- OR Continue with -";
  static const createAnAcc = 'Create An Account';
  static const signUp = '  SignUp';
  static const accountcreate = 'Create an \naccount';
  static const confirmpasshint = 'ConfirmPassword';
  static const createaccount = 'Create Account';
  static const byclicking = 'By clicking the';
  static const register = ' Register ';
  static const terms = 'button, you agree';
  static const terms2 = 'to the public offer';
  static const haveaccount = 'I Already Have an Account';
  static const emptymessage = 'Required';
  static const loginsnackbar = 'Logining In';
  static const usernamemessage = 'Only Alphabets are Allowed';
  static const passwordmessage = 'Enter Valid Password Format';
  static const confirmpassmessage= 'Does Not Match';
  static const forgetpasstext='Forget\npassword?';
  static const emailhint='Enter your email address';
  static const forgetpassmessage='* We will send you a message to set or reset your new password';
  static const submit='Submit';
  static const stylish='Stylish';
  static const font2='Libre Caslon Text';
  static const search='Search any Product..';
  static const  featured='All Featured';
  static const sort='Sort';
  static const filter='Filter';
  static const beauty='Beauty';
  static const fashion='Fashion';
  static const kids='Kids';
  static const mens='Mens';
  static const womens='Womens';
  static const off='50-40% OFF';
  static const stacktext1='Now in (product)';
  static const stacktext2='All colours';
  static const shopnow='Shop Now';
  static const stack2text1='Deal of the Day';
  static const stack2text2='22h 55m 20s remaining ';
  static const stack2text3='View all';

  
}
